apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
  annotations:
    argocd.argoproj.io/syncwave: "0" # may need to be changed
spec:
  project: default
  sources:
   - repoURL: https://repo.helmforge.dev
     chart: pihole
     targetRevision: "2.0.13"
     helm:
      valueFiles:
         - $values/infrastructure/pihole/values.yaml
   - repoURL: https://github.com/TheSiberianPunk/homelab-k3s-thing.git
     targetRevision: HEAD
     ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
     - CreateNamespace=true