apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
  annotation:
    argocd.argoproj.io/sync-wave: "1" # after traefik
spec:
  project: default
  source:
    repoURL: https://github.com/TheSiberianPunk/homelab-k3s-thing.git
    targetRevision: HEAD
    path: infrastructure/argocd-ingress/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true