apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1" 
spec:
  project: default
  source:
    repoURL: https://github.com/TheSiberianPunk/homelab-k3s-thing.git
    targetRevision: HEAD
    path: infrastructure/grafana-secret/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true