apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-media-pvc
spec:
  storageClassName: manual
  capacity:
    storage: 1800Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /vault/MEDIA
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-media-pvc
  namespace: qbittorrent
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resorces:
    requests:
      storage: 1800Gi