image:
  tag: libtorrentv1 # newer libtorrent version throttles speed at 1 Mb/s
env:
  PUID: "1000"
  PGID: "1000"
  TZ: Asia/Yekaterinburg
ingress:
  enabled: true
  className: traefik
  hosts:
   - host: qbittorrent.home
     paths:
      - path: /
        pathType: Prefix

persistence:
  config:
    enabled: true
    size: 5Gi
    storageClassName: ""

media:
  enabled: true
  existingClaim: vault-media-pvc
  mountPath: /data
  readOnly: false
