volumes:
  - name: jellyfin-tv
    hostPath:
      path: /vault/MEDIA/TV
      type: Directory
  - name: jellyfin-movies
    hostPath:
      path: /vault/MEDIA/Movies
      type: Directory
  - name: jellyfin-anime
    hostPath:
      path: /vault/MEDIA/Anime
      type: Directory

volumeMounts:
  - name: jellyfin-tv
    mountPath: /tv
    #readOnly: true
  - name: jellyfin-movies
    mountPath: /movies
    #readOnly: true
  - name: jellyfin-anime
    mountPath: /anime

persistence:
  config:
    enabled: true
    size: 5Gi
  cache:
    enabled: true
    size: 10Gi

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 2000m
    memory: 2Gi

ingress:
  enabled: true
  className: traefik
  hosts:
   - host: jellyfin.home
     paths:
      - path: /
        pathType: Prefix